    var A=document.getElementById('A');
    var B=document.getElementById('B');
    var C=document.getElementById('C');
    var D=document.getElementById('D');
    var E=document.getElementById('E');
    var F=document.getElementById('F');
    var G=document.getElementById('G');
    var H=document.getElementById('H');
    var I=document.getElementById('I');
    var J=document.getElementById('J');
    var K=document.getElementById('K');
    var L=document.getElementById('L');

    A.onclick=function(){
        A.style.display='none';
        B.style.display='block';
        C.style.display='block';
        D.style.display='none';
        E.style.display='block';
        F.style.display='none';
        G.style.display='block';
        H.style.display='none';
        I.style.display='block';
        J.style.display='none';
        K.style.display='block';
        L.style.display='none';
    }
    C.onclick=function(){
        A.style.display='block';
        B.style.display='none';
        C.style.display='none';
        D.style.display='block';
        E.style.display='block';
        F.style.display='none';
        G.style.display='block';
        H.style.display='none';
        I.style.display='block';
        J.style.display='none';
        K.style.display='block';
        L.style.display='none';
    }
    E.onclick=function(){
        A.style.display='block';
        B.style.display='none';
        C.style.display='block';
        D.style.display='none';
        E.style.display='none';
        F.style.display='block';
        G.style.display='block';
        H.style.display='none';
        I.style.display='block';
        J.style.display='none';
        K.style.display='block';
        L.style.display='none';
    }
    G.onclick=function(){
        A.style.display='block';
        B.style.display='none';
        C.style.display='block';
        D.style.display='none';
        E.style.display='block';
        F.style.display='none';
        G.style.display='none';
        H.style.display='block';
        I.style.display='block';
        J.style.display='none';
        K.style.display='block';
        L.style.display='none';
    }
    I.onclick=function(){
        A.style.display='block';
        B.style.display='none';
        C.style.display='block';
        D.style.display='none';
        E.style.display='block';
        F.style.display='none';
        G.style.display='block';
        H.style.display='none';
        I.style.display='none';
        J.style.display='block';
        K.style.display='block';
        L.style.display='none';
    }
    K.onclick=function(){
        A.style.display='block';
        B.style.display='none';
        C.style.display='block';
        D.style.display='none';
        E.style.display='block';
        F.style.display='none';
        G.style.display='block';
        H.style.display='none';
        I.style.display='block';
        J.style.display='none';
        K.style.display='none';
        L.style.display='block';
    }